# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4638bbbd1542925e067ab11f3eecdc1c"
name = "socialboost"
handle = "socialboost-2"
application_url = "https://socialboost-blue.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "socialboosttest.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/app-uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_inventory,read_marketing_events,read_orders,read_price_rules,read_products,read_reports,read_shopify_payments_payouts,write_discounts,write_inventory,write_marketing_events,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://socialboost-blue.vercel.app/api/auth/shopify/callback"
]

[pos]
embedded = false

[app_preferences]
url = "https://socialboost-blue.vercel.app/settings"
