# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce4370783ce9d18855fa2073b47f4e71"
name = "social boost"
handle = "social-boost"
application_url = "http://localhost:3000"
embedded = true

[access_scopes]
scopes = "read_orders,write_discounts,read_products,read_customers,write_products,read_inventory,write_inventory,read_analytics,read_marketing_events,write_marketing_events"

[webhooks]
api_version = "2024-01"

[auth]
redirect_urls = [
  "http://localhost:3000/api/auth/shopify/callback",
  "https://localhost:3000/api/auth/shopify/callback"
]

[pos]
embedded = false
