# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4638bbbd1542925e067ab11f3eecdc1c"
name = "socialboost"
handle = "socialboost-2"
application_url = "https://socialboost-blue.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "socialboosttest.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_inventory,read_marketing_events,read_orders,read_products,write_discounts,write_inventory,write_marketing_events,write_products"

[auth]
redirect_urls = [
  "http://localhost:3000/api/auth/shopify/callback",
  "https://localhost:3000/api/auth/shopify/callback",
  "https://socialboost-blue.vercel.app/api/auth/shopify/callback"
]

[pos]
embedded = false
