name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma client
      run: npx prisma generate
      
    - name: Run linting
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Start development server
      run: |
        # Start server in background and capture PID
        npm run dev > server.log 2>&1 &
        echo $! > server.pid
        
        # Wait for server to be ready
        timeout 60 bash -c 'until curl -f http://localhost:3000/api/test; do sleep 2; done'
        
    - name: Verify server is running
      run: |
        # Double-check server is still running
        curl -f http://localhost:3000/api/test || exit 1
        
    - name: Run app tests
      run: npm run test:app
      
    - name: Check health endpoint
      run: |
        # Test health endpoint
        curl -f http://localhost:3000/api/health || exit 1
        
    - name: Stop development server
      run: |
        # Stop server using PID
        if [ -f server.pid ]; then
          kill $(cat server.pid) || true
          rm server.pid
        fi
        # Also try to kill any remaining npm processes
        pkill -f "npm run dev" || true

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Deploy to Vercel (Preview)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        vercel-args: '--prod'

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Deploy to Vercel (Production)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        vercel-args: '--prod'
        
    - name: Deploy to Render
      run: |
        # Render deployment would go here
        # This requires Render CLI or webhook
        echo "Deploying to Render..."
        
    - name: Notify deployment
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "Production URL: ${{ secrets.PRODUCTION_URL }}" 